### ISSUE TITLE
Suggested option: Disable darkness in overlays or maximum darkness in overlays.

### ISSUE THREAD

**Issue by blake-sc** [nevir/oni-darkness-not-excluded#10]
I realized that the overlay views (pipe view whatever) are much more pleasant to use with darkness disabled. Overlays are often already pretty dark. Like supposing that "maxium darkness level = 50" is used, then the light overlay is intrinsically about as dark as unlit tiles, when darkness is applied on top of that it makes it extremely dark.

It's fine and would be balanced if overlays retain the *unlit* tile property, this is just visual darkness.

It could potentially be implemented as "min darkness in overlays" so if someone doesn't want any darkness in overlays that value can just be set to 255, and I'd also suggest that would be a good Default setting, while it can be 0 in "The Deep Dark".

**Comment by nevir** [comment]
Alright, I've just released v1.3.0 which fixes this!

(The default overlays are 50% black, so I just double the min darkness setting while in an overlay)
