### ISSUE TITLE
Dupes can't reveal some geysers with reveal radius of 4 or less

### ISSUE THREAD

**Issue by extra-salad** [nevir/oni-darkness-not-excluded#12]
Spaced Out Seed: M-RAD-C-2035056201-WDJ462-C3

With the mod off, there are two geysers revealed, Salt Water on the top right and Water on the top left:
![image](https://user-images.githubusercontent.com/87635414/236614540-792b999f-771e-42a5-ad31-f6e486fb7ab2.png)

With the mod on, if the reveal radius of a dupe is less or equals 4 then the geyser won't be revealed no matter which side the dupe is comming from:
![image](https://user-images.githubusercontent.com/87635414/236616383-e2704d14-9ffa-434b-a374-6b5242ca8ef2.png)

I assume this only happens to the geysers that are initially not burried as that water geyser on the top left is being revealed just fine with the reveal of 4 or maybe even 3, but could not confirm it working/not working with any lower values:
![image](https://user-images.githubusercontent.com/87635414/236618170-378744fc-8198-424d-af7a-17a5672bea80.png)

Also, when the place where a geyser should be is already revealed, then even after increasing the reveal radius and reloading the game, the geyser will not be able to be revealed. This happened to me on another seed where I thought I got a random empty neutronium base and only after quite a bit of cycles I realized that it's an unrevealed geyser, and the save point before exploring it was long gone.

On the side note, which probably should be a seperate issue - it seems like the changes to the mod settings are only applied on the game load? As I had to restart the game every time after changing settings to test this bug.

**Comment by extra-salad** [comment]
Just noticed (on the same seed as above) that the Supply Teleporter Input, Lab Walls, Lab Windows also don't get revealed. I had the radius set to 5 and only few of the Lab Walls/Windows got revealed. With reveal of 10 it seems to be working fine, but haven't tested anything in between.

**Comment by jacob-thanh** [comment]
If you enable sand box, you can use reveal feature of sandbox to rediscover those missing buildings or geysers, most would reappear I think, except for tiles, background buildings or buildings that been completely built over.

**Comment by nevir** [comment]
@mrn3s thank you for the detailed write-up and seed! I was struggling to reproduce this

**Comment by nevir** [comment]
Alright, I've just released v1.3.0 which fixes this!
