### ISSUE TITLE
Starting a new game in the expansion with this mod prevents any features to spawn on the map

### ISSUE THREAD

**Issue by The-Toblin** [nevir/oni-darkness-not-excluded#14]
When you start a game using this map on the expansion, your map will be devoid of any buried objects, geysers and other features of the map outside of the initial starting biome.

The only way around this is to launch the game in debug mode and trigger the "debug view" (Backspace), which, while it solves the issue, comes with a bunch of serious issues:

- It triggers the achievement block. You can no longer get any achievements in that save
- It will reveal the entire map, leading to obnoxious notifications about overheating doors in the oil biome, flooded buildings around the map and entombed features
- It is possible for this to spawn new buried objects and plants on already revealed terrain, breaking, for instance, pip planting in natural farms. These can be uprooted, of course, but it's still a hassle if you do this a few cycles in after noticing you don't have any map features.

**Comment by nevir** [comment]
Alright, I've just released v1.3.0 which fixes this!
