### ISSUE TITLE
Dupes wake up sleepers

### ISSUE THREAD

**Issue by nevir** [nevir/oni-darkness-not-excluded#16]
> My experience with barracks is that dupes take off their lighted helmets after they reach their bed, not before, so they’ll give everyone “untested - too bright” debuff on their way. So I have to be careful which bed is theirs but still it’s better to have private bedrooms early on.

**Comment by nevir** [comment]
Nyctophobic dupes should keep their intrinsic lights on, too (`component.HasTrait("NightLight")`)

**Comment by blake-sc** [comment]
Even outside the particulars of this mod, dupes getting disturbed by a passing light is something that is pretty irritating in general, and in DNE high lever miners can easily throw light at long distances through pneumatic doors. How difficult would it be to require a certain duration of light to trigger unrested or make unrested kind of like irritation so it escalates with increased exposure time?

**Comment by nevir** [comment]
Oh that's a super interesting idea - that state machine is a little tangled, but it might be feasible

**Comment by nevir** [comment]
Sweet, got that in
