### ISSUE TITLE
Spaced Out Rover doesn't have any light or reveal radius

### ISSUE THREAD

**Issue by extra-salad** [nevir/oni-darkness-not-excluded#3]
This makes it impossible to explore past the initial reveal of the planetoid

**Comment by nevir** [comment]
Doh! Yeah, I need to add support for that… will try to get that in the next update

**Comment by yandayixia** [comment]
> Doh! Yeah, I need to add support for that… will try to get that in the next update

Actually Nevir I think this is a really cool feature, less of a bug. It's mutually exclusiver from the "starting grace period" as right now though you don't get the whole map reveal for 3 cycles at the start, you do still avoid the skill penalty from being in total darkness. I think it's actually a very refreshing and fun experience to enter the game with full fog of war, while still get the grace period before darkness & its devastating -5 all skill kicks in. 

Please consider keeping this as an option! Thanks again for the wonderful mod!

**Comment by nevir** [comment]
@mrn3s  - Rover has light now, as of v1.2.0!

**Comment by nevir** [comment]
@yandayixia Definitely! The latest version has a ton more settings to play with, and I have a preset that makes it hard mode (full dark, full skill penalties, etc)

**Comment by yandayixia** [comment]
Well done my friend! Thanks for the quick response. Still waiting on the light crash to be fixed before touching ONI again. Your mod literally changed how the game works for the better. Well done!
