### ISSUE TITLE
Difficult to reveal space on starting asteroid, Atmo Suit reveal radius.

### ISSUE THREAD

**Issue by blake-sc** [nevir/oni-darkness-not-excluded#8]
Presently when you enter space on the starting asteroid you have to painstakingly reveal space.

This is not made easier by Atmo Suits presently not having any reveal radius in defaults, so if you want to reveal space you have to get a Miner to *take off* their Atmo Suit and run around naked or change the mod settings so Atmo Suit reveals.

Expected behavior: It would seem reasonable that the entire space (sunlit) area just becomes revealed automatically once a Dupe enters it.

And when a Dupe is wearing an Atmo Suit they should probably have the reveal radius set to the hat reveal radius if it's higher than the Atmosuit reveal radius. Not being able to reveal in an Atmo Suit isn't a big deal in vacuum, but is totally infeasible in like scalding hot biomes.

**Comment by nevir** [comment]
Oof, thanks for bringing this up.

So one thing I'm torn about—thematically—is whether atmo suits should be considered any differently from naked dupes. (I guess one could argue that there's some equipment in the suit; that's what we have IRL after all). But this is also one of those situations where gameplay trumps theme, too :P

For a longer term solution, I'm curious what your take would be on:

* Have atmo (and lead?) suits not override hat configs—e.g. a dupe that is actively wearing their miner hat out of suit should get the miner hat light and reveal while in suit
* Get the light-based reveal to work with sunlight (e.g. once any dupe enters space, the entire region is revealed)

And in the meantime, I'll definitely bump up atmo & lead suit reveal

**Comment by blake-sc** [comment]
While there is the logic that a hat shouldn't work inside an atmo suit, there's also the logic the dupe could put the hat on the outside of the atmo suit.

But it should also be considered that the atmosuit and jetsuit are specifically MINING SUITS, they both have +10 excavation which is a larger bonus than all the mining skills combined. So it would really be logical for them to have high level mining lights. Overpowered? Exactly, they are overpowered, it's their thing, gameplay balance seems to be that no-one should ever be disappointed at the awesomeness of atmosuits. Lead Suits do not have a mining bonus, instead having the +10 strength bonus, so there's no specific reason lead suits should have mining properties.

With respect to sunlight reveal, I can see the consistency either way. However when using Spacefarers it feels somehow wrong that they are unlit, the lit pattern is weird, and it's also not very practical to use lights in spacefarers due to space and heating constraints. I would be sympathetic to a rule that "Everything in space (with space exposure) is permanently lit independently of light".

**Comment by nevir** [comment]
> While there is the logic that a hat shouldn't work inside an atmo suit, there's also the logic the dupe could put the hat on the outside of the atmo suit.

Oh my god, I would LOVE to see that in Klei's art style, lol.

> But it should also be considered that the atmosuit and jetsuit are specifically MINING SUITS, they both have +10 excavation which is a larger bonus than all the mining skills combined. So it would really be logical for them to have high level mining lights. Overpowered? Exactly, they are overpowered, it's their thing, gameplay balance seems to be that no-one should ever be disappointed at the awesomeness of atmosuits. Lead Suits do not have a mining bonus, instead having the +10 strength bonus, so there's no specific reason lead suits should have mining properties.

Good point! Admittedly, I had totally forgotten about the +10 excavation, too. I'm sold that it's both gameplay and thematically correct to have atmosuits be the top tier of mining

**Comment by The-Toblin** [comment]
As an extension to this: This adds into the problem if you adopt the "contained base" idea and access everything outside of the core, wearing a suit. 

Early in the game, this means oxygen masks, and they also remove the effect of any hat, leading to your miners being dead blind while wearing an oxygen mask, in spite of clearly, visually, still wearing their hat. This should be amended.

**Comment by nevir** [comment]
Thanks to @ob1-games' change (https://github.com/nevir/oni-darkness-not-excluded/pull/11), this should be better: dupes wearing oxygen masks (and any other suit-like thing that lacks lights) will get their hat lights

**Comment by nevir** [comment]
And I'm hoping to get the rest of the behavior outlined here into 1.3.0

**Comment by The-Toblin** [comment]
Looking forward to it! Really, really enjoying this mod. ^^

**Comment by nevir** [comment]
Alright, I just released v1.3.0 which includes all the things we've discussed here!
